
//Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const NEW_PAIR_DATA = 'NEW_PAIR_DATA';
export const NEW_FOLLOW_TOKEN = 'NEW_FOLLOW_TOKEN';
export const NEW_AUTO_TOKEN = 'NEW_AUTO_TOKEN';